name: cd
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Deploy with SSH
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: | 
                cd /var/www/html/mkapp
                nvm use 16
                git pull origin master    
                pm2 restart ecosystem.config.js